spring:
  application:
    name: agsr-test
  datasource:
    url: jdbc:postgresql://localhost:5433/agsrtest
    username: agsrtest
    password: agsrtest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
application:
  security:
    jwt:
      secret-key: fdc66809205b21cf1b7ce7f907068597950e367796c27c13689398c5f33085f6
      expiration: 86400000 # a day